/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import member.UserDAO;
/**
 *
 * @author User
 */
public class srchForm extends javax.swing.JFrame {

    /**
     * Creates new form srchForm
     */
    public srchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSrchID = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        btnID = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnPasswd = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSrchID.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        lblSrchID.setText("<아이디 찾기>");

        lblPasswd.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        lblPasswd.setText("<비밀번호 찾기>");

        btnID.setText("아이디 찾기");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        btnPasswd.setText("비밀번호 찾기");
        btnPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswdActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        lblID.setText("아이디");

        lblEmail2.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        lblEmail2.setText("이메일");

        lblEmail.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        lblEmail.setText("이메일");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSrchID)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(txtEmail2))
                            .addGap(147, 147, 147))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblID)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(119, 119, 119)
                                    .addComponent(lblPasswd))
                                .addComponent(lblEmail2)
                                .addComponent(lblEmail))
                            .addGap(190, 190, 190)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPasswd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnID)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrchID)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnID)
                        .addComponent(lblEmail)))
                .addGap(35, 35, 35)
                .addComponent(lblPasswd)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail2)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPasswd)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        
        if ((txtEmail.getText().length() < 4) || !txtEmail.getText().contains("@") || !txtEmail.getText().contains(".")) { //이메일 형식 확인
            JOptionPane.showMessageDialog(null, "잘못된 이메일 형식입니다.");
            txtEmail.setText(null);
        }else {
        if(email.equals(""))
            JOptionPane.showMessageDialog(null, "이메일을 입력해주세요.");
        
        UserDAO userDAO = new UserDAO();
        String srchID = userDAO.srchUserID(txtEmail.getText());
        String result = userDAO.srchUserID(txtEmail.getText());
        
        if(result == null){//아이디 찾기 실패
            JOptionPane.showMessageDialog(null, "등록된 아이디가 없습니다.");
            txtEmail.setText(null);
        }else{
            JOptionPane.showMessageDialog(null, "아이디는 " + srchID + "입니다");
            txtEmail.setText(null);
            }
        }
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswdActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String email = txtEmail2.getText();
        
        if(id.equals(""))
            JOptionPane.showMessageDialog(null, "아이디를 입력해주세요.");
        
        if(email.equals(""))
            JOptionPane.showMessageDialog(null, "이메일을 입력해주세요.");
        
        if ((txtEmail2.getText().length() < 4) || !txtEmail2.getText().contains("@") || !txtEmail2.getText().contains(".")) { //이메일 형식 확인
            JOptionPane.showMessageDialog(null, "잘못된 이메일 형식입니다.");
            txtEmail2.setText(null);
        }else {
        UserDAO userDAO = new UserDAO();
        String srchPasswd = userDAO.srchUserPasswd(txtID.getText(), txtEmail2.getText());
        String result = userDAO.srchUserPasswd(txtID.getText(), txtEmail2.getText());
        
        if(result == null){//비밀번호 찾기 실패
            JOptionPane.showMessageDialog(null, "등록된 비밀번호가 없습니다.");
            txtID.setText(null);
            txtEmail2.setText(null);
        }else{
            JOptionPane.showMessageDialog(null, "비밀번호는 " + srchPasswd + "입니다");
            txtID.setText(null);
            txtEmail2.setText(null);
            }
        }
    }//GEN-LAST:event_btnPasswdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new srchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnPasswd;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblSrchID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
